# Generated by Django 4.2.6 on 2023-10-07 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(default='stable', max_length=1000)),
                ('current_floor', models.IntegerField(default=0)),
                ('destination_floor', models.JSONField(default=[])),
                ('maintaintenance', models.BooleanField(default=False)),
                ('is_running', models.BooleanField(default=True)),
                ('door_state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=1000)),
                ('elevator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jumping_minds_app.elevator')),
            ],
        ),
    ]
